version: '3'
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    environment:
      - node.name=es
      - discovery.type=single-node
      - discovery.seed_hosts=es
      - ELASTIC_PASSWORD=bombombom

      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.http.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.license.self_generated.type=basic
    volumes:
      - es-data:/usr/share/es/data
      - certs:/usr/share/elasticsearch/config/certs
    ports:
      - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200
    ports:
      - 5601:5601
    depends_on:
      - es
volumes:
  certs:
    driver: local
  es-data:
    driver: local